name: "Subtree action"
description: "Execute the git subtree action in a protected environment"

inputs:
  git_name:
    description: "Git User Name"
    required: false
    default: GitHub Actions
  git_email:
    description: "Git User Email"
    required: false
    default: actions@github.com
  repo:
    description: "Repository URL (only https path supported)"
    required: true
  ref:
    description: "Branch name, commit SHA"
    required: false
    default: "main"
  prefix:
    description: "Prefix"
    required: true
  module:
    description: "Module name"
    required: true
  github_pat:
    description: "GitHub Personal Access Token"
    required: true
  force:
    description: "Force push"
    required: false
    default: "false"

runs:
  using: "composite"

  steps:
    - name: Setup git for subtree
      shell: bash
      run: |
        # Fix dubious ownership
        git config --global --add safe.directory /github/workspace

        # Set git email and name
        git config --global user.email "${{ inputs.git_email }}"
        git config --global user.name "${{ inputs.git_name }}"

        # Configure Git for authentication
        git config --global url."https://api:${{ inputs.github_pat }}@github.com/".insteadOf "https://github.com/"
        git config --unset http."https://github.com/".extraheader

    - name: Push subtree
      shell: bash
      run: |
        set -x

        git remote add "${{ inputs.module }}" "https://github.com/${{ inputs.repo }}.git"
        git subtree add --prefix=${{ inputs.prefix }} "${{ inputs.module }}" "https://github.com/${{ inputs.repo }}.git" subtree-${{ inputs.module }}
        git subtree push-all