name: "Subtree action"
description: "Execute the git subtree action in a protected environment"

inputs:
  git_name:
    description: "Git User Name"
    required: false
    default: GitHub Actions
  git_email:
    description: "Git User Email"
    required: false
    default: actions@github.com
  repo:
    description: "Repository URL (only https path supported)"
    required: true
  position:
    description: "branch name, commit sha"
    required: false
    default: "main"
  prefix:
    description: "Prefix"
    required: true
  github_pat:
    description: "GitHub Personal Access Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: Setup git for subtree
      shell: bash
      run: |
        # Fix dubious ownership
        git config --global --add safe.directory /github/workspace

        # Set git email and name
        git config --global user.email "${{ inputs.git_email }}"
        git config --global user.name "${{ inputs.git_name }}"

        # Make sure there are no prompts for git commands
        cp .git/config .git/config-original
        git config --global url."https://api:${{ inputs.github_pat }}@github.com/".insteadOf "https://github.com/"
        git config --unset http."https://github.com/".extraheader

    - name: Setup git for subtree
      shell: bash
      run: |
        # Update subtree
        git subtree push -f --prefix=${{ inputs.prefix }} "${{ inputs.repo }}" "${{ inputs.position }}"

        # Revert git config change
        cp -f .git/config-original .git/config