name: Split and Push Changes

on:
  push:
    branches:
      - main
    paths:
      - "modules/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
      
jobs:
  get-modified-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 2 # Ensure we have enough history for the diff

      - name: Get modified modules
        id: get-modules
        run: |
          files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          folders_list="[]"

          for file in $files; do
            if [[ $file == modules/* ]]; then
              folder=$(echo "$file" | sed -E 's|^modules/([^/]+)/.*|\1|')
              folders_list=$(echo "$folders_list" | jq ". += [\"$folder\"]")
            fi
          done

          unique_list=$(echo "$folders_list" | jq -c 'unique')
          echo "modules=$unique_list" >> $GITHUB_OUTPUT
    outputs:
      modules: ${{ steps.get-modules.outputs.modules }}

  push-modified-modules:
    runs-on: ubuntu-latest
    needs: get-modified-modules
    strategy:
      matrix:
        module: ${{ fromJSON(needs.get-modified-modules.outputs.modules) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run subtree action
        id: subtree-action
        uses: ./.github/actions/subtree
        with:
          repo: christian-calabrese/terraform-aws-${{ matrix.module }}
          prefix: "modules/${{ matrix.module }}"
          module: ${{ matrix.module }}
          github_pat: ${{ secrets.SPLIT_MODULES_GH_TOKEN }}
