name: Split and Push Changes

on:
  push:
    branches:
      - main

jobs:
  split_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 2 # Ensure we have enough history for the diff

      - name: Get modified modules
        id: get-modules
        run: |
          files="$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          folders_list="[]"

          for file in $files
          do  
            folder="$(echo $(dirname "${file}") | sed 's!/*\([^/]*\).*!\1!g')"
            folders_list="$(echo "$folders_list" | jq ". += [\"$folder\"]")"
          done

          unique_list="$(echo "$folders_list" | jq -c unique )"
          echo "::set-output name=modules::$unique_list"
      
      - name: Split and push changes
        env:
          GIT_SCALAR_VERSION: "1.0"  # Specify your Git Scalar version if needed
        run: |
          modified_modules="${{ steps.get-modules.outputs.modules }}"
          if [ -z "$modified_modules" ]; then
            echo "No modules to process."
            exit 0
          fi

          for module in $modified_modules; do
            echo "Processing module: $module"

            # Define the repository URL and directory for each module
            REPO_URL="https://github.com/christian-calabrese/terraform-aws-$module.git"
            MODULE_PATH="modules/$module"
            git subtree push --prefix=$MODULE_PATH $REPO_URL main
          done